var lang_arr = new Array(
  "Afrikaans","Afrikaans",
  "Albanian","shqip",
  "Amharic","አማርኛ",
  "Arabic","العربية",
  "Armenian","Հայերեն",
  "Assamese","অসমীয়া",
  "Azerbaijani (Latin)","Azərbaycan",
  "Bangla (Bangladesh)","বাংলা (বাংলাদেশ)",
  "Bangla (India)","বাংলা (ভারত)",
  "Basque","euskara",
  "Belarusian","беларуская мова",
  "Bosnian (Latin)","bosanski",
  "Bulgarian","Български",
  "Catalan","català",
  "Central Kurdish (Arabic)","سۆرانی",
  "Cherokee","ᏣᎳᎩ ᎦᏬᏂᎯᏍᏗ",
  "Chinese Simplified","中文(简体)",
  "Chinese Traditional (Hong Kong)","中文(繁體)",
  "Chinese Traditional (Taiwan)","中文(繁體)",
  "Croatian","hrvatski",
  "Czech","čeština",
  "Danish","dansk",
  "Dari","درى",
  "Dutch","Nederlands",
  "English (United States)","English",
  "English (United Kingdom)","English",
  "Estonian","eesti",
  "Filipino","Filipino",
  "Finnish","suomi",
  "French (France)","français",
  "French (Canada)","français",
  "Galician","galego",
  "Georgian","ქართული",
  "German","Deutsch",
  "Greek","Ελληνικά",
  "Gujarati","ગુજરાતી",
  "Hausa (Latin)","Hausa",
  "Hebrew","עברית",
  "Hindi","हिंदी",
  "Hungarian","magyar",
  "Icelandic","íslenska",
  "Igbo","Ndi Igbo",
  "Indonesian","Bahasa Indonesia",
  "Irish","Gaeilge",
  "isiXhosa","isiXhosa",
  "isiZulu","isiZulu",
  "Italian","italiano",
  "Japanese","日本語",
  "Kannada","ಕನ್ನಡ",
  "Kazakh","Қазақ",
  "Khmer","ខ្មែរ",
  "K'iche'","Qatzijob'al",
  "Kinyarwanda","Ikinyarwanda",
  "KiSwahili","Kiswahili",
  "Konkani","कोंकणी",
  "Korean","한국어",
  "Kyrgyz","Кыргыз",
  "Lao","ລາວ",
  "Latvian","latviešu",
  "Lithuanian","lietuvių",
  "Luxembourgish","Lëtzebuergesch",
  "Macedonian","македонски јазик",
  "Malay (Malaysia, Brunei, and Singapore)","Bahasa Melayu",
  "Malayalam","മലയാളം",
  "Maltese","Malti",
  "Maori","Te Reo Māori",
  "Marathi","मराठी",
  "Mongolian (Cyrillic)","Монгол хэл",
  "Nepali","नेपाली",
  "Norwegian (Bokmål)","norsk (bokmål)",
  "Norwegian (Nynorsk)","norsk (nynorsk)",
  "Odia","ଓଡିଆ",
  "Persian","فارسی",
  "Polish","Polski",
  "Portuguese (Brazil)","Português",
  "Portuguese (Portugal)","português",
  "Punjabi","ਪੰਜਾਬੀ",
  "Punjabi (Arabic)","پنجابی",
  "Quechua","runasimi",
  "Romanian","română",
  "Russian","Русский",
  "Scottish Gaelic","Gàidhlig",
  "Serbian (Cyrillic, Bosnia and Herzegovina)","српски",
  "Serbian (Cyrillic, Serbia)","српски",
  "Serbian (Latin)","srpski",
  "Sesotho sa Leboa","Sesotho sa Leboa",
  "Setswana (South Africa and Botswana)","Setswana",
  "Sindhi (Arabic)","سنڌي",
  "Sinhala","සිංහල",
  "Slovak","slovenčina",
  "Slovenian","slovenski",
  "Spanish (Spain)","Español",
  "Spanish (Mexico, Latin America)","Española (América Latina)",
  "Swedish","svenska",
  "Tajik (Cyrillic)","тоҷикӣ",
  "Tamil","தமிழ்",
  "Tatar","Татар",
  "Telugu","తెలుగు",
  "Thai","ไทย",
  "Tigrinya (Ethiopia)","ትግርኛ",
  "Turkish","Türkçe",
  "Turkmen","Türkmençe",
  "Ukrainian","українська",
  "Urdu","اردو",
  "Uyghur","ئۇيغۇرچە",
  "Uzbek (Latin)","O'zbekcha",
  "Valencian","valencià",
  "Vietnamese","Tiếng Việt",
  "Welsh","Cymraeg",
  "Wolof","Wolof",
  "Yoruba","ede Yorùbá"
);